Q2. Row Echelon Form:

In [1]:
import numpy as np

In [2]:
# Setting up random seed
np.random.seed(37)

# Create a random 5x5 matrix A with integers between 0 and 9
A = np.random.randint(0, 10, size=(5, 5))

print("Original Matrix A:")
print(A)

Original Matrix A:
[[5 6 3 3 5]
 [8 5 7 8 8]
 [3 2 8 1 8]
 [3 8 4 1 3]
 [2 3 3 2 9]]


In [3]:
# Perform elementary row operations to reduce A to row echelon form
for i in range(min(A.shape)):
    # Find the pivot
    pivot_index = np.argmax(A[i:, i]) + i
    # Swap rows if necessary
    if pivot_index != i:
        A[[i, pivot_index]] = A[[pivot_index, i]]
    # Make the pivot entry 1
    A[i] = A[i] / A[i, i]
    # Eliminate entries below the pivot
    for j in range(i + 1, A.shape[0]):
        A[j] = A[j] - A[j, i] * A[i]

print("\nRow Echelon Form of Matrix A:")
print(A)


Row Echelon Form of Matrix A:
[[                   1                    0                    0
                     1                    1]
 [                   0                    1                    0
                     0                    0]
 [                   0                    0                    1
                     0                    0]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808
  -9223372036854775808 -9223372036854775808]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808
  -9223372036854775808 -9223372036854775808]]


<ipython-input-3-8eb4de6be1b0>:9: RuntimeWarning: divide by zero encountered in divide
  A[i] = A[i] / A[i, i]
<ipython-input-3-8eb4de6be1b0>:9: RuntimeWarning: invalid value encountered in divide
  A[i] = A[i] / A[i, i]
<ipython-input-3-8eb4de6be1b0>:9: RuntimeWarning: invalid value encountered in cast
  A[i] = A[i] / A[i, i]
